owner: captana
repo: status

sites:
  - name: captana.io | Frontend
    url: https://www.captana.io
    icon: https://www.captana.io/assets/media/logos/favicon.png
    maxResponseTime: 2000
  - name: captana.io | API
    url: $CAPTANAIO_API_BACKEND_CHECK
    icon: https://www.captana.io/assets/media/logos/favicon.png
    maxResponseTime: 2000

status-website:
  cname: status.captana.io
  # baseUrl: /your-repo-name # Not needed as status page is directly accesible in root of https://status.captana.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: captana status
  introTitle: "**captana** capturing and analytics"
  introMessage: This is the status page for services of [**captana.io**](https://www.captana.io)
  navbar:
    - title: status
      href: /
    - title: captana
      href: https://www.captana.io

i18n:
  footer: 2021 captana | ses-imagotag