owner: captana
repo: status

sites:
  - name: captana.io | Frontend
    url: https://www.captana.io
    icon: https://raw.githubusercontent.com/captana/status/master/assets/favicon.png
    maxResponseTime: 2000
  - name: captana.io | API
    url: $CAPTANAIO_API_BACKEND_CHECK
    icon: https://raw.githubusercontent.com/captana/status/master/assets/favicon.png
    maxResponseTime: 2000

status-website:
  cname: status.captana.io
  # baseUrl: /your-repo-name # Not needed as status page is directly accesible in root of https://status.captana.io
  # themeUrl: https://raw.githubusercontent.com/captana/status/master/assets/captana-style-dark.css # does not work as mime-type wrong -> sadly also assets folder is not copied to gh-pages
  theme: light
  favicon: https://raw.githubusercontent.com/captana/status/master/assets/favicon.png
  logoUrl: https://raw.githubusercontent.com/captana/status/master/assets/logo1.PNG
  name: " "
  introTitle: "**captana** capturing and analytics"
  introMessage: This is the status page for services of [**captana.io**](https://www.captana.io)
  navbar:
    - title: status
      href: /
    - title: captana
      href: https://www.captana.io
      
# customStatusWebsitePackage: "git+https://github.com/upptime/status-page.git"

i18n:
  footer: 2021 captana | ses-imagotag